# Application configuration
CONFIG_APP_LITTLEFS_STORAGE_BLK_SDMMC=y

# SDMMC configuration
CONFIG_GPIO=y
CONFIG_SDHC=y
CONFIG_SDMMC_STACK=y

# Disk driver configuration
CONFIG_DISK_DRIVERS=y
CONFIG_DISK_ACCESS=y
CONFIG_DISK_DRIVER_SDMMC=y

# Littlefs configuration
CONFIG_FS_LITTLEFS_BLK_DEV=y
CONFIG_FS_LITTLEFS_CACHE_SIZE=512
