# General configuration
CONFIG_REQUIRES_FULL_LIBC=y
CONFIG_POSIX_API=y
CONFIG_SHELL=y
# RTC configuration
CONFIG_RTC=y
CONFIG_RTC_SHELL=y

# Network configuration
CONFIG_NETWORKING=y
CONFIG_NET_IPV4=y
CONFIG_NET_UDP=y
CONFIG_NET_SHELL=y

# Socket configuration
CONFIG_NET_SOCKETS=y
CONFIG_NET_SOCKETS_POLL_MAX=16

# Network driver configuration
CONFIG_TEST_RANDOM_GENERATOR=y

# SNTP configuration
CONFIG_SNTP=y
CONFIG_NET_CONFIG_CLOCK_SNTP_INIT=y
CONFIG_NET_CONFIG_SNTP_INIT_SERVER="192.168.10.1"

# Stack size
CONFIG_MAIN_STACK_SIZE=2048

# Logging configuration
CONFIG_NET_LOG=y
CONFIG_LOG=y
CONFIG_LOG_MODE_IMMEDIATE=y
# CONFIG_NET_SOCKETS_LOG_LEVEL_INF=y
CONFIG_SNTP_LOG_LEVEL_INF=y
CONFIG_RTC_LOG_LEVEL_INF=y
