image: registry.sysfly.co:15000/ze-runner:v2
stages:
  - setup
  - lint
  - build

setup_env:
  stage: setup
  script:
    - . ~/zephyrproject/.venv/bin/activate
    - |
      if [ ! -d "../.west" ]; then
        west init -l . --mf west.yml
      fi
    - west config --global update.narrow true
    - west config --global update.fetch smart
    - git config --global https.proxy "http://192.168.31.2:7890"
    - git config --global http.proxy "http://192.168.31.2:7890"
    - west update
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always

Coding_guidelines:
  stage: lint
  script:
    - . ~/zephyrproject/.venv/bin/activate
    - export ZEPHYR_BASE=$PWD
    - ./scripts/ci/guideline_check.py -c $CI_MERGE_REQUEST_DIFF_BASE_SHA...$CI_COMMIT_SHA
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always

Devicetree_Scripts_Test:
  stage: lint
  script:
    - . ~/zephyrproject/.venv/bin/activate
    - cd scripts/dts/python-devicetree && tox
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always

Compliance_Checks:
  stage: lint
  script:
    - . ~/zephyrproject/.venv/bin/activate
    - ./scripts/ci/check_compliance.py -c $CI_MERGE_REQUEST_DIFF_BASE_SHA...$CI_COMMIT_SHA
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always

Manifest:
  stage: lint
  script:
    - . ~/zephyrproject/.venv/bin/activate
    - python .gitlab/scripts/manifest_check.py $CI_MERGE_REQUEST_DIFF_BASE_SHA $CI_COMMIT_SHA
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always

Scorecards_supply_chain_security:
  stage: lint
  script:
    - scorecard --local .
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always

codecov:
  stage: build
  script:
    - . ~/zephyrproject/.venv/bin/activate
    - export ZEPHYR_BASE=$PWD
    - export ZEPHYR_TOOLCHAIN_VARIANT=zephyr
    - export ZEPHYR_SDK_INSTALL_DIR=$HOME/toolchain/zephyr-sdk-0.16.8
    - env
    - ls $ZEPHYR_SDK_INSTALL_DIR
    - mkdir -p coverage/reports
    - pip3 install gcovr==6.0
    - ./scripts/twister -E qemu_x86-testplan.json
    - |
      ./scripts/twister -i --force-color -N -v --filter runnable -p qemu_x86 \
        --coverage -T tests/kernel/sched --coverage-tool gcovr \
        -xCONFIG_TEST_EXTRA_STACK_SIZE=4096 -e nano --timeout-multiplier 2
    - mv twister-out/coverage.json coverage/reports/qemu_x86.json
  artifacts:
    paths:
      - coverage/reports/qemu_x86.json
      - qemu_x86-testplan.json
    expire_in: 1 week
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always

codecov-results:
  stage: build
  needs: [codecov]
  script:
    - . ~/zephyrproject/.venv/bin/activate
    - mkdir -p coverage/reports
    - ls -lRt ./coverage/reports
    - pip3 install gcovr==6.0
    - pushd ./coverage/reports
    - gcovr --add-tracefile qemu_x86.json --merge-mode-functions=separate --json merged.json
    - gcovr --add-tracefile qemu_x86.json --merge-mode-functions=separate --cobertura merged.xml
    - popd
    - export RUN_DATE=$(date +'%Y-%m-%d')
    - pip install xlsxwriter ijson
    - |
      python3 ./scripts/ci/coverage/coverage_analysis.py -t qemu_x86-testplan.json \
        -m MAINTAINERS.yml -c coverage/reports/merged.json \
        -o coverage-report-${RUN_DATE} -f all
    - cp coverage-report-* coverage/reports/
  artifacts:
    paths:
      - coverage/reports/merged.json
      - coverage/reports/merged.xml
      - coverage/reports/coverage-report-*.json
      - coverage/reports/coverage-report-*.xlsx
    expire_in: 1 week
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always
