# shell options
CONFIG_SHELL=y

# Generic kernel options
CONFIG_MAIN_STACK_SIZE=4096
CONFIG_COMMON_LIBC_MALLOC=y
CONFIG_HEAP_MEM_POOL_SIZE=1048576
CONFIG_COMMON_LIBC_MALLOC_ARENA_SIZE=2097152

# Logging
CONFIG_LOG=y
CONFIG_ASSERT=n
CONFIG_PRINTK=y
CONFIG_LOG_SPEED=n
CONFIG_LOG_BUFFER_SIZE=4096
CONFIG_LOG_PROCESS_THREAD_SLEEP_MS=50
CONFIG_LOG_BLOCK_IN_THREAD=y
CONFIG_LOG_CMDS=y

# For SDMMC/MMC read/write
CONFIG_SDHC=y
CONFIG_GPIO=y
CONFIG_DISK_DRIVER_SDMMC=y

# For FatFS support
CONFIG_DISK_ACCESS=y
CONFIG_LOG=y
CONFIG_FILE_SYSTEM=y
CONFIG_FAT_FILESYSTEM_ELM=y
CONFIG_FS_FATFS_LFN=y
CONFIG_PRINTK=y

# For NOR FLASH Support
CONFIG_SPI=y
CONFIG_SPI_NOR=y
CONFIG_FLASH=y
CONFIG_FLASH_CAD_FLASH_QSPI_NOR=y

# For u-boot support
CONFIG_UBOOT=y
