# empty config

# ARM options
# Reason: NMI handler is an optional feature that is not used by safety-critical applications.
CONFIG_RUNTIME_NMI=n
CONFIG_FP16=n

# Interrupt configuration (No debug/exception handling)
CONFIG_GEN_ISR_TABLES=n
CONFIG_EXCEPTION_DEBUG=n

# Cache options
CONFIG_DCACHE=n
CONFIG_ICACHE=n

# Kernel options
CONFIG_ERRNO=n
CONFIG_CURRENT_THREAD_USE_TLS=n
CONFIG_BOOT_BANNER=n
CONFIG_TIMESLICING=n # WARN: disables preemption, this may affect some subsystems (e.g. networking)
CONFIG_KERNEL_MEM_POOL=n
CONFIG_TICKLESS_KERNEL=n # NOTE: tickless is more efficient but also increases handling logic complexity (+400 code size)

# Drivers (optional, without this, there will be no any outputs on serial port)
CONFIG_CONSOLE=n
CONFIG_SERIAL=n
CONFIG_PINCTRL_FMQL=n
CONFIG_CLOCK_CONTROL_FMSH=n

# Virtual memory support
CONFIG_MMU=n
CONFIG_ARM_AARCH32_MMU=n

# libc options
CONFIG_MINIMAL_LIBC=y
CONFIG_COMMON_LIBC_MALLOC=n
CONFIG_MINIMAL_LIBC_TIME=n

# utilities
CONFIG_CBPRINTF_N_SPECIFIER=n
CONFIG_CBPRINTF_NANO=n

# debug options
CONFIG_STACK_SENTINEL=n
CONFIG_ASSERT_VERBOSE=n
CONFIG_NO_RUNTIME_CHECKS=y
