# kernel options
CONFIG_SCHED_SCALABLE=y # optimized for performance and scalability for 20+ threads
CONFIG_THREAD_RUNTIME_STATS_OVERFLOW_PROTECTION=y # fixup overflow issue in runtime stats
CONFIG_STATIC_INIT_GNU=y # make sure global static c++ objects are initialized

# debug options
CONFIG_ASSERT=y # enable assert for debugging
CONFIG_DEBUG_THREAD_INFO=y # improve debug experience by providing thread info for GDB
CONFIG_SYMTAB=y # application can access symbol table for self-diagnosis

# logging options (depends on CONFIG_LOG)
CONFIG_LOG_SPEED=y
CONFIG_LOG_PROCESS_THREAD_SLEEP_MS=100 # reduce log processing interval to improve responsiveness
CONFIG_LOG_THREAD_ID_PREFIX=y # include thread ID in log messages
CONFIG_LOG_INFO_COLOR_GREEN=y # use green color for info logs
CONFIG_LOG_DBG_COLOR_BLUE=y # use blue color for debug logs

# build options
CONFIG_BUILD_OUTPUT_COMPRESS_DEBUG_SECTIONS=y # compress debug sections to reduce binary size
CONFIG_MISRA_SANE=y # enable MISRA C compliance checks
CONFIG_FORTIFY_SOURCE_RUN_TIME=y # enable runtime checks for buffer overflows
CONFIG_COMPILER_WARNINGS_AS_ERRORS=y
CONFIG_DEBUG_OPTIMIZATIONS=y # Optimizing for size will reduce code size but may affect performance,
                             # and optimize for debug is a better choice than optimize for performance
