CONFIG_SERIAL=y

# async api support
CONFIG_UART_ASYNC_API=y

# DMA support
CONFIG_DMA=y
CONFIG_HEAP_MEM_POOL_SIZE=1024

# NS16550 driver config
CONFIG_UART_NS16550=y
CONFIG_UART_NS16550_ACCESS_WORD_ONLY=y
CONFIG_UART_NS16550_DESIGNWARE_DMA=y

# DesignWare DMA 64bit support
CONFIG_DMA_64BIT=n

# RTT console support
CONFIG_USE_SEGGER_RTT=y
CONFIG_CONSOLE=y
CONFIG_RTT_CONSOLE=y
CONFIG_UART_CONSOLE=n

# RTT buffer config
CONFIG_SEGGER_RTT_MODE_NO_BLOCK_SKIP=y
CONFIG_SEGGER_RTT_BUFFER_SIZE_UP=4096
CONFIG_SEGGER_RTT_BUFFER_SIZE_DOWN=16
CONFIG_SEGGER_RTT_PRINTF_BUFFER_SIZE=64

# log setting
CONFIG_PRINTK=y
CONFIG_LOG=y
CONFIG_LOG_BACKEND_RTT=y
CONFIG_LOG_BACKEND_UART=n
CONFIG_LOG_MODE_IMMEDIATE=y


# enable dma detailed log
# CONFIG_DMA_LOG_LEVEL_DBG=y
