# Logging
CONFIG_LOG=y
CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_LOG_ALWAYS_RUNTIME=y
CONFIG_PRINTK=y

# Shell options
CONFIG_SHELL=y
CONFIG_SHELL_STACK_SIZE=16384
CONFIG_IDLE_STACK_SIZE=2048

# SSL options
CONFIG_WOLFSSL=y
CONFIG_WOLFSSL_BUILTIN=y
CONFIG_POSIX_THREADS=y
CONFIG_POSIX_API=n
CONFIG_TEST_RANDOM_GENERATOR=y
CONFIG_WOLFSSL_SETTINGS_FILE="inc/wolfssl_settings.h"

# Enable wolfTPM
CONFIG_WOLFTPM=y

# GmSSL minimal configuration for SM3 algorithm only
CONFIG_GMSSL=y
CONFIG_GMSSL_SDF=n
CONFIG_GMSSL_TLS=n
CONFIG_GMSSL_SHA1=n
CONFIG_GMSSL_SHA2=n
CONFIG_GMSSL_AES=n
CONFIG_GMSSL_CHACHA20=n
CONFIG_GMSSL_SM4_ECB=n
CONFIG_GMSSL_SM4_OFB=n
CONFIG_GMSSL_SM4_CFB=n
CONFIG_GMSSL_SM4_CCM=n
CONFIG_GMSSL_SM4_XTS=n
CONFIG_GMSSL_SM4_CBC_MAC=n
CONFIG_GMSSL_SM2_EXTS=n
CONFIG_GMSSL_SM3_XMSS=n

# Flash support
CONFIG_FLASH=y
CONFIG_GPIO=y
CONFIG_SPI=y
CONFIG_SPI_DW=y
CONFIG_SPI_DW_ACCESS_WORD_ONLY=y
CONFIG_SPI_NOR=y
CONFIG_SPI_NOR_FLASH_LAYOUT_PAGE_SIZE=256
CONFIG_SPI_NOR_SFDP_DEVICETREE=y

# 设备绑定支持
CONFIG_DEVICE_SHELL=y

# Generic kernel options
CONFIG_MAIN_STACK_SIZE=4096
CONFIG_HEAP_MEM_POOL_SIZE=26214400
CONFIG_COMMON_LIBC_MALLOC_ARENA_SIZE=26214400
