CONFIG_LOG=y
CONFIG_LOG_MODE_DEFERRED=y
CONFIG_LOG_BACKEND_UART=y
CONFIG_LOG_BACKEND_FS=y
CONFIG_LOG_BACKEND_FS_DIR="/lfs"
CONFIG_LOG_BACKEND_FS_FILE_SIZE=1048576
CONFIG_LOG_BACKEND_FS_FILES_LIMIT=4
CONFIG_LOG_BACKEND_FS_DEGRADE_FAILURE_THRESHOLD=3
CONFIG_LOG_BACKEND_FS_DEGRADE_PRINTK_INTERVAL_MS=5000
CONFIG_LOG_MAX_LEVEL=4

CONFIG_PRINTK=y
CONFIG_MAIN_STACK_SIZE=8192
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=8192

CONFIG_FILE_SYSTEM=y
CONFIG_FILE_SYSTEM_LITTLEFS=y
